### ISSUE TITLE
아직 번역이 되지 않은 단어가 있을 때 다른 브랜치에서 push 하면 번역되지 않은 단어가 transifex에서 사라지는 현상

### ISSUE THREAD

**Issue by heejongahn** [spoqa/aeiou#5]
실제로 추측하고 있는 내용이 맞는지 확인하고, 맞다면 고칠 방법을 생각해봐야 함

**Comment by disjukr** [comment]
그 뿐만 아니라 번역 돼있어도 날리는 것 같습니다.

**Comment by disjukr** [comment]
[이 로직대로](https://docs.transifex.com/projects/updating-content#what-happens-when-you-update-files)면 문제가 없어야 할텐데 ㅁㄴㅇㄹ... 걍 aeiou 수준에서 병합해서 올려줘야할 듯
